# Generated by Django 2.0.5 on 2021-03-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Id', models.IntegerField(max_length=10)),
                ('Contact', models.IntegerField(max_length=10)),
                ('Address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
